from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import ClassVar
from uuid import UUID, uuid4


@dataclass(frozen=True, slots=True)
class Event:
    """
    Base class for all domain events.

    Events are:
    - immutable
    - timestamped in UTC
    - uniquely identifiable
    - safe to replay and audit
    """

    # Unique event identifier
    event_id: UUID

    # UTC timestamp of event creation
    timestamp_utc: datetime

    # Event type name (static per subclass)
    event_type: ClassVar[str]

    @classmethod
    def create(cls, **kwargs) -> "Event":
        """
        Factory method to create a new event with
        autogenerated ID and timestamp.
        """
        return cls(
            event_id=uuid4(),
            timestamp_utc=datetime.now(timezone.utc),
            **kwargs,
        )
